In [1]:
import pandas as pd
import os
import math
import numpy as np
import cx_Oracle
from config import oracle_wfm_key
import time
import datetime as dt
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
from sqlalchemy.types import String
from tqdm import tqdm
import itertools
import databases as db
from decimal import Decimal, getcontext
from math import ceil, exp, floor

In [2]:
ods = db.oracle('cco_wfm',oracle_wfm_key)
verint  = db.ssms()
service = ['BSSC Billing ALL (new)','BSSC Senior','Commercial COAST','Mooresville_BSSC_Billing','BSSC Sales Cable','BSSC Sales Wireline','Mooresville_BSSC_Sales',
            'Bend/Cable Consumer Sales','OB_QCB Bend/Cable Sales','Cable Specialist','OB_OCB_Cable_Con_Spec','Cable Sales Seniors',
            'Financial Services Res','Financial Services Bus',
            'Wireline Sales and Service','Wireline Service QCB','Wireline Consumer Specialist','Wireline Consumer Triage','Wireline Retention QCB','Wireline Senior Specialist 1']
start = '2023-01-01 00:00:00.000'
end = '2023-03-31 23:45:00.000'
appended_data = []
for name in service:
    new_query = f'''SELECT 
                        [Queue],
                        [DateTime],
                        [Actual_CV],
                        [Forecasted_CV],
                        [Actual_AHT],
                        [Forecasted_AHT],
                        [Required_FTE]                                              
                    FROM [BPMAINDB].[dbo].[V_AdHoc_PerformanceStatistics]
                    WHERE ([Queue] = '{name}') AND ([DateTime] BETWEEN '{start}' AND '{end}')
                    AND ([UserName] = 'satverintwrkoptmgmt')'''
    data = pd.read_sql(new_query, verint)
    appended_data.append(data)
appended_data = pd.concat(appended_data)
appended_data.tail(3)

,Queue,DateTime,Actual_CV,Forecasted_CV,Actual_AHT,Forecasted_AHT,Required_FTE
8633,Wireline Senior Specialist 1,2023-03-31 23:15:00,0.0,NaN,0.0,NaN,NaN
8634,Wireline Senior Specialist 1,2023-03-31 23:30:00,0.0,NaN,0.0,NaN,NaN
8635,Wireline Senior Specialist 1,2023-03-31 23:45:00,0.0,NaN,0.0,NaN,NaN

In [3]:
team_dict = {'BSSC Billing ALL (new)' : 'Commercial_Billing','BSSC Senior' : 'Commercial_Billing','Commercial COAST' : 'Commercial_Billing','Mooresville_BSSC_Billing' : 'Commercial_Billing',
        'BSSC Sales Cable' : 'Commercial_Sales','BSSC Sales Wireline' : 'Commercial_Sales','Mooresville_BSSC_Sales' : 'Commercial_Sales',
        'Bend/Cable Consumer Sales' : 'Cable_Sales','OB_QCB Bend/Cable Sales' : 'Cable_Sales','Cable Specialist' : 'Cable_Retention','OB_OCB_Cable_Con_Spec' : 'Cable_Retention',
        'Cable Sales Seniors' : 'Cable_Seniors',
        'Financial Services Res' : 'Residential_FS','Financial Services Bus' : 'Commercial_FS',
        'Wireline Sales and Service' : 'Wireline_Sales','Wireline Service QCB' : 'Wireline_Sales',
        'Wireline Consumer Specialist' : 'Wireline_Retention','Wireline Consumer Triage' : 'Wireline_Retention','Wireline Retention QCB' : 'Wireline_Retention',
        'Wireline Senior Specialist 1': 'Wireline_Seniors'}
appended_data['Team'] = appended_data['Queue'].map(team_dict)
appended_data = appended_data.reindex(columns=['Team'] + list(appended_data.columns[:-1]))
appended_data.tail(3)

,Team,Queue,DateTime,Actual_CV,Forecasted_CV,Actual_AHT,Forecasted_AHT,Required_FTE
8633,Wireline_Seniors,Wireline Senior Specialist 1,2023-03-31 23:15:00,0.0,NaN,0.0,NaN,NaN
8634,Wireline_Seniors,Wireline Senior Specialist 1,2023-03-31 23:30:00,0.0,NaN,0.0,NaN,NaN
8635,Wireline_Seniors,Wireline Senior Specialist 1,2023-03-31 23:45:00,0.0,NaN,0.0,NaN,NaN

In [4]:
appended_data['Actual_Workload'] = appended_data['Actual_AHT'] * appended_data['Actual_CV']
appended_data['Actual_Workload'] = appended_data['Actual_Workload'].replace(0, np.nan)
appended_data['Forecasted_Workload'] = appended_data['Forecasted_AHT'] * appended_data['Forecasted_CV']
appended_data['Forecasted_Workload'] = appended_data['Forecasted_Workload'].replace(0, np.nan)

In [5]:
team = ['Commercial_Billing','Commercial_Sales','Cable_Sales','Cable_Retention','Cable_Seniors','Residential_FS','Commercial_FS',
        'Wireline_Sales','Wireline_Retention','Wireline_Seniors']
dfs = []
for t in team:
    team_group = appended_data.loc[(appended_data['Team']  == t)]
    actual_cv = team_group.groupby(['Team','DateTime'])['Actual_CV'].sum()
    actual_cv = actual_cv.reset_index()
    actual_cv.set_index('DateTime', inplace=True) # set the index to the 'DateTime' column
    actual_cv = actual_cv.resample('30 min').sum() # remove the 'on' parameter
    actual_cv.reset_index(inplace=True)
    actual_cv.set_index('DateTime', inplace=True)
    
    forecasted_cv = team_group.groupby(['Team','DateTime'])['Forecasted_CV'].sum()
    forecasted_cv = forecasted_cv.reset_index()
    forecasted_cv.set_index('DateTime', inplace=True) # set the index to the 'DateTime' column
    forecasted_cv = forecasted_cv.resample('30 min').sum() # remove the 'on' parameter
    forecasted_cv.reset_index(inplace=True)
    forecasted_cv.set_index('DateTime', inplace=True)
    
    grouped_aht = team_group.groupby(['Team','DateTime'])['Actual_Workload'].sum()
    grouped_aht = grouped_aht.reset_index()
    grouped_aht['Actual_Workload'] = grouped_aht['Actual_Workload'].replace(0, np.nan)
    grouped_aht.set_index('DateTime', inplace=True) # set the index to the 'DateTime' column
    grouped_aht = grouped_aht.resample('30 min').sum() # remove the 'on' parameter
    grouped_cv = team_group.groupby(['Team','DateTime'])['Actual_CV'].sum()
    grouped_cv = grouped_cv.reset_index()
    grouped_cv.set_index('DateTime', inplace=True) # set the index to the 'DateTime' column
    grouped_cv = grouped_cv.resample('30 min').sum() # remove the 'on' parameter
    actual_aht = grouped_aht.merge(grouped_cv, on='DateTime', how='left')
    actual_aht['Actual_AHT'] = actual_aht['Actual_Workload'] / actual_aht['Actual_CV']
    actual_aht = actual_aht.drop(columns=['Actual_Workload','Actual_CV'])
    actual_aht.reset_index(inplace=True)
    actual_aht.set_index('DateTime', inplace=True)
    actual_aht['Actual_AHT'] = actual_aht['Actual_AHT'].fillna(0)
    actual_aht['Actual_AHT'] = round(actual_aht['Actual_AHT'])
    
    grouped_faht = team_group.groupby(['Team','DateTime'])['Forecasted_Workload'].sum()
    grouped_faht = grouped_faht.reset_index()
    grouped_faht['Forecasted_Workload'] = grouped_faht['Forecasted_Workload'].replace(0, np.nan)
    grouped_faht.set_index('DateTime', inplace=True) # set the index to the 'DateTime' column
    grouped_faht = grouped_faht.resample('30 min').sum() # remove the 'on' parameter
    grouped_fcv = team_group.groupby(['Team','DateTime'])['Forecasted_CV'].sum()
    grouped_fcv = grouped_fcv.reset_index()
    grouped_fcv.set_index('DateTime', inplace=True) # set the index to the 'DateTime' column
    grouped_fcv = grouped_fcv.resample('30 min').sum() # remove the 'on' parameter
    forecasted_aht = grouped_faht.merge(grouped_fcv, on='DateTime', how='left')
    forecasted_aht['Forecasted_AHT'] = forecasted_aht['Forecasted_Workload'] / forecasted_aht['Forecasted_CV']
    forecasted_aht = forecasted_aht.drop(columns=['Forecasted_Workload','Forecasted_CV'])
    forecasted_aht.reset_index(inplace=True)
    forecasted_aht.set_index('DateTime', inplace=True)
    forecasted_aht['Forecasted_AHT'] = forecasted_aht['Forecasted_AHT'].fillna(0)
    forecasted_aht['Forecasted_AHT'] = round(forecasted_aht['Forecasted_AHT'])
    
    # req_fte = team_group.groupby(['Team','DateTime'])['Required_FTE'].mean()
    # req_fte = req_fte.reset_index()
    # req_fte.set_index('DateTime', inplace=True) # set the index to the 'DateTime' column
    # req_fte = req_fte.resample('30 min').mean() # remove the 'on' parameter
    # req_fte.reset_index(inplace=True)
    # req_fte.set_index('DateTime', inplace=True)
    # req_fte['Required_FTE'] = req_fte['Required_FTE'].fillna(0).apply(math.ceil)
    
    cv = actual_cv.merge(forecasted_cv, on=['DateTime'], how='left')
    aht = actual_aht.merge(forecasted_aht, on=['DateTime'], how='left')
    table = cv.merge(aht, on=['DateTime'], how='left')
    # table = table.merge(req_fte, on=['DateTime'], how='left')
    table['Team'] = t
    table = table.reindex(columns=['Team'] + list(table.columns[:-1]))
    dfs.append(table)

result = pd.concat(dfs)
result.head()

,Team,Actual_CV,Forecasted_CV,Actual_AHT,Forecasted_AHT
DateTime,,,,,
2023-01-01 00:00:00,Commercial_Billing,0.0,0.0,0.0,0.0
2023-01-01 00:30:00,Commercial_Billing,0.0,0.0,0.0,0.0
2023-01-01 01:00:00,Commercial_Billing,0.0,0.0,0.0,0.0
2023-01-01 01:30:00,Commercial_Billing,0.0,0.0,0.0,0.0
2023-01-01 02:00:00,Commercial_Billing,0.0,0.0,0.0,0.0

In [6]:
result.reset_index(inplace=True)
result['Date'] = result['DateTime'].dt.date
result['Time'] = result['DateTime'].dt.time
result = result.drop('DateTime', axis=1)
result['Time_Interval'] = '00:30'
result = result[['Team', 'Date', 'Time', 'Time_Interval', 'Actual_CV', 'Forecasted_CV', 'Actual_AHT', 'Forecasted_AHT']]
result.head()

,Team,Date,Time,Time_Interval,Actual_CV,Forecasted_CV,Actual_AHT,Forecasted_AHT
0,Commercial_Billing,2023-01-01,00:00:00,00:30,0.0,0.0,0.0,0.0
1,Commercial_Billing,2023-01-01,00:30:00,00:30,0.0,0.0,0.0,0.0
2,Commercial_Billing,2023-01-01,01:00:00,00:30,0.0,0.0,0.0,0.0
3,Commercial_Billing,2023-01-01,01:30:00,00:30,0.0,0.0,0.0,0.0
4,Commercial_Billing,2023-01-01,02:00:00,00:30,0.0,0.0,0.0,0.0

In [7]:
team_settings = {
    'Commercial_Billing': (0.60, 0.05),
    'Commercial_Sales': (0.60, 0.05),
    'Cable_Sales': (0.65, 0.05),
    'Cable_Retention': (0.65, 0.05),
    'Cable_Seniors': (0.70, 0.05),
    'Residential_FS': (0.65, 0.05),
    'Commercial_FS': (0.65, 0.05),
    'Wireline_Sales': (0.65, 0.10),
    'Wireline_Retention': (0.65, 0.10),
    'Wireline_Seniors': (0.70, 0.05)
}


# set the constant variables
Reporting_Period = 30
service_level_time = 30

## Erlang Testing

In [18]:
class ErlangC:
    def __init__(self, transactions, aht, asa, interval, shrinkage=0.0):
        if not (0 < aht < float('inf')) or not (0 < asa < float('inf')) or not (0 < interval < float('inf')) or not (0 <= shrinkage < 1):
            raise ValueError("Invalid input values")

        self.n_transactions = transactions
        self.aht = aht
        self.interval = interval
        self.asa = asa
        self.intensity = (self.n_transactions / self.interval) * self.aht
        self.shrinkage = shrinkage

    def waiting_probability(self, positions, scale_positions=False):
        if scale_positions:
            productive_positions = floor((1 - self.shrinkage) * positions)
        else:
            productive_positions = positions

        erlang_b_inverse = 1
        for position in range(1, productive_positions + 1):
            erlang_b_inverse = 1 + (erlang_b_inverse * position / self.intensity)

        erlang_b = 1 / erlang_b_inverse
        return productive_positions * erlang_b / (productive_positions - self.intensity * (1 - erlang_b))

    def service_level(self, positions, scale_positions=False):
        if scale_positions:
            productive_positions = floor((1 - self.shrinkage) * positions)
        else:
            productive_positions = positions

        probability_wait = self.waiting_probability(productive_positions, scale_positions=False)
        exponential = exp(-(productive_positions - self.intensity) * (self.asa / self.aht))
        return max(0, 1 - (probability_wait * exponential))

    def achieved_occupancy(self, positions, scale_positions=False):
        if scale_positions:
            productive_positions = floor((1 - self.shrinkage) * positions)
        else:
            productive_positions = positions

        return self.intensity / productive_positions

    def required_positions(self, service_level, max_occupancy=1.0):
        positions = round(self.intensity + 1)
        achieved_service_level = self.service_level(positions, scale_positions=False)
        while achieved_service_level < service_level:
            positions += 1
            achieved_service_level = self.service_level(positions, scale_positions=False)

        achieved_occupancy = self.achieved_occupancy(positions, scale_positions=False)
        raw_positions = ceil(positions)

        if achieved_occupancy > max_occupancy:
            raw_positions = ceil(self.intensity / max_occupancy)
            achieved_occupancy = self.achieved_occupancy(raw_positions)
            achieved_service_level = self.service_level(raw_positions)

        waiting_probability = self.waiting_probability(positions=raw_positions)
        positions = ceil(raw_positions / (1 - self.shrinkage))

        return {"raw_positions": raw_positions,
                "positions": positions,
                "service_level": achieved_service_level,
                "occupancy": achieved_occupancy,
                "waiting_probability": waiting_probability}

def calculate_agents_v2(calls, reporting_period, average_handling_time, service_level_percent, service_level_time, shrinkage):
    if math.isnan(calls) or math.isnan(reporting_period) or math.isnan(average_handling_time) or math.isnan(service_level_percent) or math.isnan(service_level_time) or math.isnan(shrinkage) or calls == 0 or average_handling_time == 0:
        return float('nan')

    if not (0 < calls < float('inf')) or not (0 < reporting_period < float('inf')) or not (0 < average_handling_time < float('inf')) or not (0 <= service_level_percent <= 1) or not (0 < service_level_time < float('inf')) or not (0 <= shrinkage < 1):
        raise ValueError(f"Invalid input values: calls={calls}, reporting_period={reporting_period}, average_handling_time={average_handling_time}, service_level_percent={service_level_percent}, service_level_time={service_level_time}, shrinkage={shrinkage}")

    asa = service_level_time / 60  # Convert seconds to minutes
    interval = reporting_period * 60  # Convert hours to minutes

    erlang_c_instance = ErlangC(transactions=calls, aht=average_handling_time, asa=asa, interval=interval, shrinkage=shrinkage)
    required_positions_data = erlang_c_instance.required_positions(service_level=service_level_percent)

    # print(f"calls: {calls}, reporting_period: {reporting_period}, average_handling_time: {average_handling_time}, service_level_percent: {service_level_percent}, service_level_time: {service_level_time}, shrinkage: {shrinkage}")
    # print(f"asa: {asa}, interval: {interval}")
    # print(f"required_positions_data: {required_positions_data}")

    return required_positions_data['positions']

In [8]:
# Loop through the DataFrame
for index, row in result.iterrows():
    team = row['Team']
    shrinkage, service_level_percent = team_settings[team]

    forecasted_cv = row['Forecasted_CV']
    forecasted_aht = row['Forecasted_AHT']
    actual_cv = row['Actual_CV']
    actual_aht = row['Actual_AHT']

    required_fte_forecast = calculate_agents_v2(forecasted_cv, Reporting_Period, forecasted_aht, service_level_percent, service_level_time, shrinkage)
    required_fte_actual = calculate_agents_v2(actual_cv, Reporting_Period, actual_aht, service_level_percent, service_level_time, shrinkage)

    result.at[index, 'Required_FTE_Forecast'] = required_fte_forecast
    result.at[index, 'Required_FTE_Actual'] = required_fte_actual

In [9]:
directory = "I:\\GitHub\\forecasting\\accuracy\\accuracy_exports\\"
result['Date'] = pd.to_datetime(result['Date'])
result['Month'] = result['Date'].dt.strftime('%Y-%m')
teams = result['Team'].unique()
for team in teams:
    team_result = result[result['Team'] == team]
    for month in team_result['Month'].unique():
        month_result = team_result[team_result['Month'] == month]
        file_name = f"{team}_{month}.txt"
        file_path = os.path.join(directory, file_name)
        month_result.to_csv(file_path, sep='\t', index=False)

In [23]:
# Sample data
sample_data = [
    (4, 343),
    (5, 725),
    (10, 469),
    (14, 394),
    (9, 498),
    (16, 638),
    (16, 659),
    (14, 748),
    (6, 713),
    (17, 451),
    (15, 666),
    (14, 872),
    (15, 539),
    (11, 527),
    (15, 602),
    (12, 658),
    (22, 829),
    (18, 533),
    (10, 442),
    (2, 570),
    (7, 243),
    (2, 1089),
    (1, 711),
]

# Constants
service_level_percent = 0.60
shrinkage = 0.05
reporting_period = 30
service_level_time = 30

# Collect the results in a list
results = []
for calls, handle_time in sample_data:
    erlang_c = ErlangC(calls, reporting_period, handle_time, service_level_time, shrinkage)
    required_positions_data = erlang_c.required_positions(service_level_percent)
    results.append((calls, handle_time, *required_positions_data.values()))

# Create a DataFrame with the results
column_names = ['calls', 'handle_time', 'raw_positions', 'positions', 'service_level', 'occupancy', 'waiting_probability']
df = pd.DataFrame(results, columns=column_names)

# Display the DataFrame
df

,calls,handle_time,raw_positions,positions,service_level,occupancy,waiting_probability
0,4,343,5,6,0.999994,0.800000,0.554113
1,5,725,6,7,1.000000,0.833333,0.587516
2,10,469,11,12,1.000000,0.909091,0.682118
3,14,394,15,16,0.999999,0.933333,0.722319
4,9,498,10,11,1.000000,0.900000,0.668732
5,16,638,17,18,1.000000,0.941176,0.737183
6,16,659,17,18,1.000000,0.941176,0.737183
7,14,748,15,16,1.000000,0.933333,0.722319
8,6,713,7,8,1.000000,0.857143,0.613830
9,17,451,18,19,1.000000,0.944444,0.743726
10,15,666,16,17,1.000000,0.937500,0.730076
11,14,872,15,16,1.000000,0.933333,0.722319
12,15,539,16,17,1.000000,0.937500,0.730076
13,11,527,12,13,1.000000,0.916667,0.693902
14,15,602,16,17,1.000000,0.937500,0.730076
15,12,658,13,14,1.000000,0.923077,0.704388
16,22,829,23,25,1.000000,0.956522,0.770141
17,18,533,19,20,1.000000,0.947368,0.749779
18,10,442,11,12,1.000000,0.909091,0.682118
19,2,570,3,4,1.000000,0.666667,0.444444
20,7,243,8,9,0.999807,0.875000,0.635316
21,2,1089,3,4,1.000000,0.666667,0.444444
22,1,711,2,3,1.000000,0.500000,0.333333

In [53]:
class ErlangC:
    def __init__(self, calls, reporting_period, aht, service_level_time, shrinkage):
        self.calls = calls
        self.reporting_period = reporting_period
        self.aht = aht
        self.service_level_time = service_level_time
        self.shrinkage = shrinkage
        self.intensity = self.traffic_intensity()

    def traffic_intensity(self):
        return (self.calls * self.aht) / self.reporting_period

    @staticmethod
    def erlang_c_formula(intensity, positions):
        getcontext().prec = 50
        decimal_intensity = Decimal(intensity)
        decimal_positions = Decimal(positions)
        numerator = (decimal_intensity ** decimal_positions) / Decimal(math.factorial(positions))
        denominator = Decimal(0)
        for k in range(0, positions):
            denominator += (decimal_intensity ** Decimal(k)) / Decimal(math.factorial(k))

        if decimal_positions == decimal_intensity:
            return 1.0
        
        denominator += (numerator * (decimal_positions / (decimal_positions - decimal_intensity)))
        return float(numerator / denominator)

    def waiting_probability(self, positions, scale_positions=True):
        if scale_positions:
            productive_positions = ceil(positions * (1 - self.shrinkage))
        else:
            productive_positions = positions

        return ErlangC.erlang_c_formula(self.intensity, productive_positions)

    def service_level(self, positions, scale_positions=True):
        if scale_positions:
            positions = ceil(positions / (1 - self.shrinkage))
        probability_wait = self.waiting_probability(positions, scale_positions=False)
        exponential = exp(-(positions - self.intensity) * (self.service_level_time / self.aht))
        return max(0, 1 - probability_wait * exponential)


    def occupancy(self, positions, scale_positions=True):
        if scale_positions:
            productive_positions = ceil(positions * (1 - self.shrinkage))
        else:
            productive_positions = positions

        return self.intensity / productive_positions

    def required_positions(self, service_level, max_occupancy=1.0):
        positions = ceil(self.intensity)
        achieved_service_level = self.service_level(positions, scale_positions=False)

        while achieved_service_level < service_level:
            positions += 1
            achieved_service_level = self.service_level(positions, scale_positions=False)

        self.positions = positions
        achieved_service_level = self.service_level(positions, scale_positions=True)  # Adjusted
        achieved_occupancy = self.occupancy(positions)

        return {
            "raw_positions": positions,
            "positions": ceil(positions / (1 - self.shrinkage)),
            "service_level": achieved_service_level,
            "occupancy": achieved_occupancy,
            "waiting_probability": self.waiting_probability(positions, scale_positions=False),
        }


def calculate_agents_v2(calls, reporting_period, average_handling_time, service_level_percent, service_level_time, shrinkage):
    if math.isnan(calls) or math.isnan(reporting_period) or math.isnan(average_handling_time) or math.isnan(service_level_percent) or math.isnan(service_level_time) or math.isnan(shrinkage) or calls == 0 or average_handling_time == 0:
        return float('nan')

    if not (0 < calls < float('inf')) or not (0 < reporting_period < float('inf')) or not (0 < average_handling_time < float('inf')) or not (0 <= service_level_percent <= 1) or not (0 < service_level_time < float('inf')) or not (0 <= shrinkage < 1):
        raise ValueError(f"Invalid input values: calls={calls}, reporting_period={reporting_period}, average_handling_time={average_handling_time}, service_level_percent={service_level_percent}, service_level_time={service_level_time}, shrinkage={shrinkage}")

    asa = service_level_time / 60  # Convert seconds to minutes
    interval = reporting_period * 60  # Convert hours to minutes

    erlang_c_instance = ErlangC(transactions=calls, aht=average_handling_time, asa=asa, interval=interval, shrinkage=shrinkage)
    required_positions_data = erlang_c_instance.required_positions(service_level=service_level_percent)

    # print(f"calls: {calls}, reporting_period: {reporting_period}, average_handling_time: {average_handling_time}, service_level_percent: {service_level_percent}, service_level_time: {service_level_time}, shrinkage: {shrinkage}")
    # print(f"asa: {asa}, interval: {interval}")
    # print(f"required_positions_data: {required_positions_data}")

    return required_positions_data['positions']

In [54]:
# Sample data
sample_data = [
    (4, 343),
    (5, 725),
    (10, 469),
    (14, 394),
    (9, 498),
    (16, 638),
    (16, 659),
    (14, 748),
    (6, 713),
    (17, 451),
    (15, 666),
    (14, 872),
    (15, 539),
    (11, 527),
    (15, 602),
    (12, 658),
    (22, 829),
    (18, 533),
    (10, 442),
    (2, 570),
    (7, 243),
    (2, 1089),
    (1, 711),
]

# Constants
service_level_percent = 0.60
shrinkage = 0.05
reporting_period = 30
service_level_time = 30

# Collect the results in a list
results = []
for calls, handle_time in sample_data:
    erlang_c = ErlangC(calls, reporting_period, handle_time, service_level_time, shrinkage)
    required_positions_data = erlang_c.required_positions(service_level_percent)
    results.append((calls, handle_time, *required_positions_data.values()))

# Create a DataFrame with the results
column_names = ['calls', 'handle_time', 'raw_positions', 'positions', 'service_level', 'occupancy', 'waiting_probability']
df = pd.DataFrame(results, columns=column_names)

# Display the DataFrame
df

,calls,handle_time,raw_positions,positions,service_level,occupancy,waiting_probability
0,4,343,46,49,0.973280,1.039394,0.005526
1,5,725,121,128,0.982877,1.050725,0.001352
2,10,469,157,166,0.989335,1.042222,0.003975
3,14,394,184,194,0.991473,1.050667,0.000716
4,9,498,150,158,0.987709,1.044755,0.003764
5,16,638,341,359,0.995140,1.050206,0.002047
6,16,659,352,371,0.995358,1.049154,0.001463
7,14,748,350,369,0.995013,1.048248,0.002506
8,6,713,143,151,0.985177,1.048529,0.002684
9,17,451,256,270,0.994406,1.047404,0.001637
10,15,666,334,352,0.995068,1.047170,0.002796
11,14,872,407,429,0.995299,1.051507,0.000163
12,15,539,270,285,0.994150,1.048638,0.001783
13,11,527,194,205,0.991152,1.044505,0.003690
14,15,602,302,318,0.994513,1.048780,0.003082
15,12,658,264,278,0.992707,1.048606,0.002850
16,22,829,608,640,0.997923,1.051788,0.000109
17,18,533,320,337,0.995218,1.051974,0.000616
18,10,442,148,156,0.988489,1.044917,0.004209
19,2,570,39,42,0.967446,1.000000,0.020995
20,7,243,57,60,0.979280,1.030909,0.005014
21,2,1089,73,77,0.974407,1.037143,0.005173
22,1,711,24,26,0.956082,1.030435,0.011609